(()=>{'use strict';
const C=window.SafetyCore,$=id=>document.getElementById(id),app=$('app');
let qs=[],docs=[],byId={},state=C.empty(),db,view='home',review=null,writeChain=Promise.resolve(),broken=false,offline=false,reg=null,updateReady=false,filterType='',filterCat='',docSearch='',questionSearch='',currentDoc=null,questionOpened=Date.now(),saveStatus='本机保存',busy=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>new Date(t).toLocaleString('zh-CN',{hour12:false});
const uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
const btn=(text,action,cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;
const active=()=>review||state.session;
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
function fatal(e){broken=true;notice('本机记录暂时无法保存：'+e.message+'。请先导出备份，再重新打开；继续作答已暂停。');saveStatus='保存异常';document.querySelector('.local-tag').textContent=saveStatus;}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('safety-c1-pocket',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('请先关闭其他刷题页面'));});}
function readState(){return new Promise((resolve,reject)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function save(){
 if(broken)return Promise.reject(Error('保存已暂停'));
 const snapshot=structuredClone(state),expected=state.revision;state.revision++;snapshot.revision=state.revision;
 const task=writeChain.then(()=>new Promise((resolve,reject)=>{let conflict=false;const tx=db.transaction('state','readwrite'),store=tx.objectStore('state');const r=store.get('main');r.onsuccess=()=>{if((r.result?.revision||0)!==expected){conflict=true;tx.abort();return;}store.put(snapshot,'main');};tx.oncomplete=()=>resolve();tx.onabort=()=>reject(Error(conflict?'另一窗口已更新记录，请关闭其他窗口并重新打开':tx.error?.message||'写入中断'));tx.onerror=()=>{};}));
 writeChain=task;task.catch(fatal);return task;
}
function navigate(v){view=v;review=null;currentDoc=null;render();scrollTo(0,0);}
function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===(view==='quiz'?'home':view==='result'?'history':view)));if(view==='home')home();else if(view==='quiz')quiz();else if(view==='result')result();else if(view==='history')history();else if(view==='docs')documents();else settings();}
function home(){
 const answered=state.attempts.filter(a=>a.kind!=='reveal'),correct=answered.filter(a=>a.correct).length;
 app.innerHTML=`<section class="panel hero"><h1>今天，从一道题开始</h1><div class="stats"><div class="stat"><b>${Object.keys(state.done).filter(id=>!id.startsWith('case-')).length}<small style="font-size:13px;font-weight:400"> / 2965</small></b><span>已练习题目</span></div><div class="stat"><b>${answered.length?Math.round(correct/answered.length*100)+'%':'—'}</b><span>累计作答正确率</span></div><div class="stat"><b>${state.exams.length}</b><span>模拟考试</span></div></div>${state.session?btn('继续上次'+(state.session.mode==='exam'?'考试':'练习'),'resume','primary full')+'<p class="muted" style="color:#d4e2fa;margin:10px 0 0">'+esc(state.session.label)+' · 第 '+(state.session.pos+1)+' / '+state.session.queue.length+' 题</p>':btn('开始顺序练习','sequential','primary full')}</section>
 <div class="cards"><button class="tile" data-action="exam"><b>模拟考试</b><span>90 分钟 · 100 分</span></button><button class="tile" data-action="random"><b>随机练习</b><span>打乱题目顺序</span></button><button class="tile" data-action="wrong"><b>错题本 <span>${state.wrong.length}</span></b><span>集中复习薄弱题目</span></button><button class="tile" data-action="favorites"><b>我的收藏 <span>${state.fav.length}</span></b><span>保留需要再看的题</span></button></div>
 <section class="panel"><h2>按题型和知识点练习</h2><div class="fields"><label>题型<select id="type-filter"><option value="">全部基础题型</option>${['单选题','多选题','判断题','案例题'].map(t=>`<option ${filterType===t?'selected':''}>${t}</option>`).join('')}</select></label><label>知识分类<select id="cat-filter"><option value="">全部分类</option>${[...new Set(qs.map(q=>q.c))].sort().map(c=>`<option ${filterCat===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><div class="row" style="margin-top:16px">${btn('开始筛选练习','filtered','primary')}${btn('顺序练习','sequential')}</div></section>
 <section class="panel"><h2>搜索题目</h2><label class="visually-hidden" for="question-search">搜索题干和选项</label><input type="search" id="question-search" placeholder="搜索题干或选项，如：防坠安全器" value="${esc(questionSearch)}"><div id="question-results"></div></section><p class="muted">基础题 2,965 道，另含 6 个案例、24 道小题。学习记录保存在当前设备。</p>`;renderSearch();
}
function renderSearch(){const el=$('question-results');if(!el)return;const term=questionSearch.trim();if(term.length<2){el.innerHTML='<p class="muted" style="margin-top:12px">输入至少 2 个字。</p>';return;}const hits=qs.filter(q=>(q.q+' '+q.o.join(' ')).includes(term));el.innerHTML=`<p class="muted">找到 ${hits.length} 道题，显示前 60 道</p>`+hits.slice(0,60).map(q=>`<button class="list-btn" data-action="search-open" data-id="${esc(q.n)}">${esc(q.q.slice(0,100))}${q.q.length>100?'…':''}<small>${esc(q.s)} · ${esc(q.c)}</small></button>`).join('');}
async function start(queue,label,mode='practice'){
 if(!queue.length){notice('这里暂时没有题目。');return false;}
 if(state.session&&!confirm('开始新的'+(mode==='exam'?'考试':'练习')+'会替换当前未完成进度，已经保存的作答记录仍会保留。继续吗？'))return false;
 const now=Date.now();state.session={id:uuid(),mode,label,queue:queue.map(String),pos:0,answers:{},checked:{},startedAt:now,endAt:mode==='exam'?now+90*60000:0};await save();review=null;view='quiz';questionOpened=Date.now();render();scrollTo(0,0);return true;
}
function quiz(){const s=active();if(!s){navigate('home');return;}const id=s.queue[s.pos],q=byId[id],checked=!!s.checked[id]||!!review,picked=s.answers[id]||[],multi=q.s==='多选题';
 app.innerHTML=`<div class="row between section-top">${btn(review?'返回成绩':'返回练习页',review?'back-result':'home','small')}<span class="timer" id="timer"></span></div><section class="panel"><div class="row between"><div class="row"><span class="pill">${esc(q.s)}</span><span class="muted">${s.pos+1} / ${s.queue.length}</span></div>${btn(state.fav.includes(id)?'★ 已收藏':'☆ 收藏','favorite','small',`aria-pressed="${state.fav.includes(id)}"`)}</div><div class="progress"><i style="width:${(s.pos+1)/s.queue.length*100}%"></i></div><p class="muted" style="margin:12px 0 0">${esc(q.c)}${multi?' · 选择全部正确选项':''}</p><div class="q-stem">${esc(q.q)}</div><div role="group" aria-label="答案选项">${q.o.map((o,i)=>{const letter=String.fromCharCode(65+i);let cls=picked.includes(letter)?' selected':'';if(checked){if(q.a.includes(letter))cls+=' correct';else if(picked.includes(letter))cls+=' incorrect';}return `<button class="option${cls}" data-action="pick" data-letter="${letter}" aria-pressed="${picked.includes(letter)}" ${checked?'disabled':''}><b>${letter}</b><span>${esc(o)}</span></button>`;}).join('')}</div>${checked?`<div class="feedback ${C.same(picked,q.a)?'':'bad'}">${s.revealed?.[id]?'已查看答案':C.same(picked,q.a)?'回答正确':'回答错误'}<br>你的答案：${esc(picked.join('')||'未作答')}　正确答案：<strong>${esc(q.a)}</strong></div>`:''}<div class="row">${!checked&&s.mode!=='exam'?btn('提交答案','submit','primary',picked.length?'':'disabled')+btn('查看答案','reveal'):''}${state.wrong.includes(id)?btn('标为已掌握','mastered','small'):''}</div></section><div class="row between">${btn('上一题','prev','',s.pos===0?'disabled':'')}${btn(s.pos===s.queue.length-1?(review?'返回成绩':s.mode==='exam'?'交卷':'完成练习'):'下一题','next','primary')}</div><section class="panel" style="margin-top:16px"><details><summary>答题卡</summary><p class="muted">显示当前题目前后最多 100 题</p><div class="grid">${s.queue.slice(Math.floor(s.pos/100)*100,Math.floor(s.pos/100)*100+100).map((qid,j)=>{const p=Math.floor(s.pos/100)*100+j,ck=s.checked[qid]||review;return `<button data-action="jump" data-pos="${p}" class="${p===s.pos?'current ':''}${ck?(C.same(s.answers[qid]||[],byId[qid].a)?'correct':'incorrect'):s.answers[qid]?.length?'done':''}">${p+1}</button>`;}).join('')}</div></details></section>${s.mode==='exam'&&!review?btn('提前交卷','finish','full')+'<p class="muted">选择后自动保存，交卷前可以修改答案。退出应用后考试计时继续。</p>':''}`;tick();
}
async function record(kind){const s=state.session;if(!s)return;const id=s.queue[s.pos],q=byId[id];if(s.checked[id])return;const selected=s.answers[id]||[];if(!selected.length&&kind!=='reveal')return;
 const correct=C.same(selected,q.a);s.checked[id]=true;
 if(kind==='reveal'){s.revealed=s.revealed||{};s.revealed[id]=true;}else state.done[id]=true;
 if(!correct&&!state.wrong.includes(id))state.wrong.push(id);
 state.attempts.push({id:uuid(),sessionId:s.id,questionId:id,selected:[...selected],correct,kind,at:Date.now(),elapsedMs:Math.max(0,Date.now()-questionOpened)});await save();quiz();
}
async function finish(auto=false){const s=state.session;if(!s||s.mode!=='exam'||state.exams.some(e=>e.id===s.id))return;if(!auto&&!confirm(`还有 ${s.queue.filter(id=>!s.answers[id]?.length).length} 道题未作答，确定交卷吗？`))return;
 const now=Date.now();for(const id of s.queue){const selected=s.answers[id]||[],correct=C.same(selected,byId[id].a);s.checked[id]=true;if(selected.length)state.done[id]=true;if(!correct&&!state.wrong.includes(id))state.wrong.push(id);state.attempts.push({id:uuid(),sessionId:s.id,questionId:id,selected:[...selected],correct,kind:'exam',at:now,elapsedMs:0});}
 const e={...structuredClone(s),...C.score(s,byId),finishedAt:now,durationMs:Math.min(90*60000,Math.max(0,now-s.startedAt))};state.exams.push(e);state.session=null;await save();review=e;view='result';render();scrollTo(0,0);if(auto)notice('考试时间已到，已自动交卷并保存在本机。');
}
function result(){const e=review;if(!e){navigate('history');return;}app.innerHTML=`<section class="panel"><p class="muted">模拟考试成绩 · ${date(e.finishedAt)}</p><div class="score">${e.score}<span style="font-size:20px"> / ${e.total}</span></div><h2 style="margin-top:12px">${e.score/e.total>=.6?'达到 60% 合格线':'继续复习，再试一次'}</h2><p class="muted">${e.legacy?'旧版导入记录，没有每题明细。':`答对 ${e.correct} / ${e.queue.length} 题 · 用时 ${Math.ceil(e.durationMs/60000)} 分钟`}</p><div class="row">${btn('查看历史考试','history')}${!e.legacy?btn('重做本次错题','redo-exam','primary'):''}</div></section>${!e.legacy?`<section class="panel"><h2>答题回看</h2><div class="grid">${e.queue.map((id,p)=>`<button class="${C.same(e.answers[id]||[],byId[id].a)?'correct':'incorrect'}" data-action="review-jump" data-pos="${p}">${p+1}</button>`).join('')}</div></section>`:''}`;}
function history(){const a=state.attempts.filter(a=>a.kind!=='reveal');app.innerHTML=`<h1 class="section-top">学习记录</h1><section class="panel"><h2>累计作答 ${a.length} 次</h2><p class="muted">答对 ${a.filter(x=>x.correct).length} 次 · 错题本 ${state.wrong.length} 道<br>重复练习按实际作答次数统计，查看答案不计入正确率。</p></section><section class="panel"><h2>模拟考试 · ${state.exams.length} 次</h2>${state.exams.length?state.exams.slice().reverse().map(e=>`<button class="list-btn" data-action="exam-history" data-id="${esc(e.id)}"><strong>${e.score} / ${e.total} 分</strong><small>${date(e.finishedAt)}${e.legacy?' · 旧版记录':''}</small></button>`).join(''):'<p class="empty">完成第一次模拟考试后，成绩会保存在这里。</p>'}</section><section class="panel"><h2>最近作答</h2>${state.attempts.length?state.attempts.slice(-50).reverse().map(a=>`<button class="list-btn" data-action="attempt-detail" data-id="${esc(a.id)}"><span class="${a.correct?'ok-text':'error-text'}">${a.kind==='reveal'?'查看答案':a.correct?'答对':'答错'}</span> · ${esc(byId[a.questionId].q.slice(0,65))}<small>${date(a.at)} · ${a.kind==='exam'?'模拟考试':'练习'} · 所选 ${esc(a.selected.join('')||'未作答')}</small></button>`).join(''):'<p class="empty">你的每次作答都会自动记录。</p>'}<p class="muted">页面显示最近 50 条；导出备份包含全部记录。</p></section>`;}
function documents(){if(currentDoc!==null){showDocument(currentDoc);return;}const list=docs.filter(d=>(d.title+' '+d.path).includes(docSearch));app.innerHTML=`<h1 class="section-top">学习资料</h1><p class="muted">54 篇资料 · 离线准备完成后可断网阅读</p><section class="panel"><label for="doc-search">按标题查找</label><input id="doc-search" type="search" value="${esc(docSearch)}" placeholder="如：塔式起重机"><div id="doc-results">${docList(list)}</div></section>`;}
const docList=list=>list.map(d=>`<button class="list-btn" data-action="doc" data-id="${d.id}">${esc(d.title.replace(/^\d+_/,''))}<small>${esc(d.path.split('/').slice(0,-1).join('/')||'总览与专项')}</small></button>`).join('')||'<p class="empty">没有找到对应资料。</p>';
function showDocument(id){const d=docs.find(d=>d.id===id);if(!d)return;currentDoc=id;app.innerHTML=`<div class="section-top">${btn('返回资料目录','docs','small')}</div><article class="panel doc" id="doc-body"></article>`;const template=document.createElement('template');template.innerHTML=d.html;template.content.querySelectorAll('script,iframe,object,embed,form,style,link,meta').forEach(el=>el.remove());template.content.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes])if(a.name.startsWith('on')||['srcdoc','style'].includes(a.name))el.removeAttribute(a.name);});
 template.content.querySelectorAll('a').forEach(a=>{const raw=a.getAttribute('href')||'';if(raw.startsWith('#'))return;if(/^https?:\/\//i.test(raw)){a.target='_blank';a.rel='noopener noreferrer';return;}let path;try{path=decodeURIComponent(new URL(raw,'https://local/'+d.path).pathname.slice(1));}catch{}const target=docs.find(x=>x.path===path);a.removeAttribute('href');if(target){a.href='#';a.dataset.action='doc';a.dataset.id=target.id;}else{a.title='此链接指向资料包中的原始文件';}});template.content.querySelectorAll('img,video,audio,source').forEach(el=>el.remove());$('doc-body').append(template.content);$('doc-body').querySelectorAll('table').forEach(t=>{const wrapper=document.createElement('div');wrapper.className='table-wrap';t.before(wrapper);wrapper.append(t);});}
function settings(){app.innerHTML=`<h1 class="section-top">离线与备份</h1><section class="panel"><h2>安装到 iPhone 主屏幕</h2><ol><li>用 <strong>Safari</strong> 打开此页面。</li><li>点"分享"→"添加到主屏幕"；若出现"作为网页 App 打开"，请开启。</li><li>从主屏幕图标进入，等待下方显示"离线资源已就绪"。</li><li>开启飞行模式，重新打开，确认能刷题和阅读资料。</li></ol><p class="muted">建议以后固定从主屏幕进入。同一网址的浏览器窗口和主屏幕应用可能使用不同存储；已有记录请用备份迁移。</p></section><section class="panel"><h2>离线资源</h2><p id="offline-status" class="${offline?'ok-text':'muted'}">${offline?'离线资源已就绪 · 题库和资料已保存在本机':'正在检查离线资源…'}</p><div class="row">${btn('检查离线准备','offline-check')}${updateReady?btn('更新应用','update','primary'):''}</div><p class="muted">首次下载或恢复离线资源需要联网。系统清理缓存后，需要重新下载。</p></section><section class="panel"><h2>备份学习记录</h2><p>备份包含全部作答、错题、收藏、考试成绩和当前进度。</p><div class="row">${btn('导出备份','export','primary')}${btn('恢复备份','import')}</div><p class="muted" style="margin-top:12px">${state.lastBackup?'最近生成备份：'+date(state.lastBackup):'还没有生成过备份。'}<br>导出后请确认文件已保存。可选"存储到文件"→"我的 iPhone"；换手机前再复制到其他设备。</p><p class="muted">记录只在本机，不会上传。清除网站数据或移除应用可能丢失记录，建议定期备份。</p></section><section class="panel"><h2>本机数据</h2><p class="muted">${state.attempts.length} 条作答 · ${state.exams.length} 次考试 · ${state.fav.length} 道收藏</p>${btn('清空所有学习记录','reset','danger')}<p class="muted" style="margin-top:12px">题库版本：广东 C1 第六批 · 应用 1.0<br>资料和考试规则沿用原资料包，本次仅改造程序。</p></section>`;}
async function exportBackup(){await writeChain.catch(()=>{});const when=Date.now(),data=structuredClone(state);data.lastBackup=when;const file=new File([JSON.stringify({format:'safety-c1-backup',exportedAt:when,data},null,2)],'安全员C1-学习备份-'+new Date().toISOString().slice(0,10)+'.json',{type:'application/json'});let shared=false;
 if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'安全员 C1 学习备份'});shared=true;}catch(e){if(e.name==='AbortError')return;}}
 if(!shared){const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 if(!broken){state.lastBackup=when;await save();}notice('备份文件已生成，请确认已保存到"文件"。');if(view==='settings')settings();
}
async function restore(file){if(!file)return;if(file.size>50*1024*1024)throw Error('备份超过 50 MB');const raw=JSON.parse(await file.text());if(raw.format!=='safety-c1-backup')throw Error('不是本应用的备份文件');const data=C.validate(raw.data,byId);if(!confirm(`此备份有 ${data.attempts.length} 条作答、${data.exams.length} 次考试。恢复会替换当前学习记录，建议先导出当前备份。确定恢复吗？`))return;await writeChain;data.revision=state.revision;state=data;await save();navigate('home');notice('备份已恢复。');}
async function offlineCheck(){if(!reg)throw Error('离线服务尚未启动，请联网重新打开');if(reg.waiting)updateReady=true;const worker=reg.active;if(!worker){notice('正在下载题库和资料，请保持页面打开。');return;}const response=await new Promise((resolve,reject)=>{const ch=new MessageChannel();const timeout=setTimeout(()=>reject(Error('离线检查超时，请联网重试')),10000);ch.port1.onmessage=e=>{clearTimeout(timeout);resolve(e.data);};worker.postMessage({type:'CHECK_OFFLINE'},[ch.port2]);});offline=!!response.ready;if(view==='settings')settings();if(!offline)notice('离线资源尚未完整保存，请保持联网并重新打开页面。');}
async function setupOffline(){try{if(!('serviceWorker'in navigator))throw Error('请使用支持离线应用的 Safari');reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});const watch=w=>{if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='activated')offlineCheck().catch(e=>notice(e.message));if(w.state==='installed'&&navigator.serviceWorker.controller){updateReady=true;if(view==='settings')settings();}});};watch(reg.installing);reg.addEventListener('updatefound',()=>watch(reg.installing));if(reg.active)await offlineCheck();if(reg.waiting){updateReady=true;if(view==='settings')settings();}navigator.serviceWorker.ready.then(()=>offlineCheck().catch(e=>notice(e.message)));if(navigator.storage?.persist)await navigator.storage.persist();}catch(e){notice('离线准备未完成：'+e.message+'。请保持联网后重试。');}}
function tick(){const s=state.session;if(!s||s.mode!=='exam'||broken)return;const left=Math.max(0,s.endAt-Date.now()),el=$('timer');if(el&&!review)el.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor(left%60000/1000)).padStart(2,'0')}`;if(!left&&!busy){busy=true;finish(true).catch(fatal).finally(()=>busy=false);}}
async function action(a,b){
 const safe=['export','offline-check','home','settings','docs','history','doc','exam-history','review-jump','back-result','attempt-detail'];if(broken&&!safe.includes(a)){notice('保存异常，请先导出备份并重新打开应用。');return;}
 if(['home','history','docs','settings'].includes(a)){navigate(a);return;}
 if(a==='sequential')return start(qs.filter(q=>q.s!=='案例题').map(q=>q.n),'顺序练习');
 if(a==='random')return start(C.shuffle(qs.filter(q=>q.s!=='案例题').map(q=>q.n)),'随机练习');
 if(a==='filtered')return start(qs.filter(q=>(filterType?q.s===filterType:q.s!=='案例题')&&(!filterCat||q.c===filterCat)).map(q=>q.n),(filterType||'基础题')+' · '+(filterCat||'全部分类'));
 if(a==='wrong')return start(state.wrong,'错题复习');if(a==='favorites')return start(state.fav,'收藏练习');
 if(a==='exam'){if(!confirm('开始模拟考试：单选 50、多选 10、判断 18、案例小题 12，共 100 分，90 分钟。开始后退出应用仍继续计时。'))return;return start(C.examQueue(qs),'模拟考试','exam');}
 if(a==='resume'){review=null;view='quiz';questionOpened=Date.now();render();return;}
 if(a==='search-open'){const hits=qs.filter(q=>(q.q+' '+q.o.join(' ')).includes(questionSearch.trim())).map(q=>String(q.n));const started=await start(hits,'搜索练习');if(started&&state.session?.label==='搜索练习'&&state.session.queue.includes(b.dataset.id)){state.session.pos=state.session.queue.indexOf(b.dataset.id);await save();quiz();}return;}
 if(a==='doc'){view='docs';showDocument(Number(b.dataset.id));scrollTo(0,0);return;}
 if(a==='exam-history'){review=structuredClone(state.exams.find(e=>e.id===b.dataset.id));view='result';render();scrollTo(0,0);return;}
 if(a==='review-jump'){if(!review)return;review.pos=Number(b.dataset.pos);view='quiz';render();scrollTo(0,0);return;}
 if(a==='back-result'){view='result';render();return;}
 if(a==='redo-exam'){const e=review;return start(e.queue.filter(id=>!C.same(e.answers[id]||[],byId[id].a)),'本次考试错题');}
 if(a==='attempt-detail'){const x=state.attempts.find(x=>x.id===b.dataset.id);if(!x)return;alert(byId[x.questionId].q+'\n\n所选：'+(x.selected.join('')||'未作答')+'\n正确答案：'+byId[x.questionId].a+'\n'+date(x.at));return;}
 if(a==='export')return exportBackup();if(a==='import'){$('restore-file').value='';$('restore-file').click();return;}
 if(a==='offline-check'){await offlineCheck();if(offline)notice('离线资源已就绪。请从主屏幕进入后，用飞行模式实测一次。');return;}
 if(a==='update'){if(reg?.waiting&&confirm('更新会重新打开应用，已保存记录会保留。现在更新吗？')){await writeChain;let reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloaded){reloaded=true;location.reload();}});reg.waiting.postMessage({type:'SKIP_WAITING'});}return;}
 if(a==='reset'){if(!confirm('确定清空本机全部学习记录？题库和资料会保留。'))return;if(prompt('请输入"清空"确认。建议先导出备份。')!=='清空')return;const rev=state.revision;state=C.empty();state.revision=rev;await save();navigate('home');return;}
 const s=active();if(!s)return;const id=s.queue[s.pos],q=byId[id];
 if(a==='favorite'){state.fav=state.fav.includes(id)?state.fav.filter(x=>x!==id):[...state.fav,id];await save();quiz();return;}
 if(a==='mastered'){state.wrong=state.wrong.filter(x=>x!==id);await save();quiz();return;}
 if(a==='prev'||a==='next'||a==='jump'){let pos=a==='jump'?Number(b.dataset.pos):s.pos+(a==='prev'?-1:1);if(pos>=s.queue.length){if(review){view='result';render();return;}if(s.mode==='exam')return finish();state.session=null;await save();navigate('home');notice('本组练习已完成，作答记录已保存。');return;}s.pos=Math.max(0,pos);if(!review)await save();questionOpened=Date.now();quiz();scrollTo(0,0);return;}
 if(review)return;
 if(s.mode==='exam'&&Date.now()>=s.endAt)return finish(true);
 if(a==='pick'&&!s.checked[id]){const letter=b.dataset.letter,prev=s.answers[id]||[];s.answers[id]=q.s==='多选题'?(prev.includes(letter)?prev.filter(x=>x!==letter):[...prev,letter].sort()):[letter];await save();quiz();return;}
 if(a==='submit')return record('practice');if(a==='reveal'&&confirm('查看答案将计入复习记录，但不计入作答正确率。继续吗？'))return record('reveal');if(a==='finish')return finish();
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action],[data-nav]');if(!b)return;e.preventDefault();if(busy)return;busy=true;try{if(b.dataset.nav)navigate(b.dataset.nav);else await action(b.dataset.action,b);}catch(e){notice(e.message);}finally{busy=false;}});
document.addEventListener('change',e=>{if(e.target.id==='type-filter')filterType=e.target.value;if(e.target.id==='cat-filter')filterCat=e.target.value;});
document.addEventListener('input',e=>{if(e.target.id==='question-search'){questionSearch=e.target.value;renderSearch();}if(e.target.id==='doc-search'){docSearch=e.target.value;$('doc-results').innerHTML=docList(docs.filter(d=>(d.title+' '+d.path).includes(docSearch)));}});
$('restore-file').addEventListener('change',e=>restore(e.target.files[0]).catch(e=>notice('无法恢复：'+e.message)));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});window.addEventListener('online',()=>{if(reg)offlineCheck().catch(()=>{});});
async function init(){try{
 const response=await Promise.all([fetch('./questions.json'),fetch('./documents.json')]);if(response.some(r=>!r.ok))throw Error('题库或资料下载失败');[qs,docs]=await Promise.all(response.map(r=>r.json()));byId=Object.fromEntries(qs.map(q=>[String(q.n),q]));db=await openDB();db.onversionchange=()=>{db.close();fatal(Error('应用数据版本已改变，请重新打开'));};const stored=await readState();
 if(stored){state=C.validate(stored,byId);state.revision=stored.revision||0;}else{try{const old=JSON.parse(localStorage.getItem('aqC1_v1')||'null');if(old){state.wrong=(old.wrong||[]).map(String).filter(id=>byId[id]);state.fav=(old.fav||[]).map(String).filter(id=>byId[id]);for(const id of Object.keys(old.done||{}))if(byId[id])state.done[id]=true;state.exams=(old.hist||[]).filter(e=>Number.isFinite(e.score)).map(e=>({id:uuid(),legacy:true,finishedAt:Date.parse(e.d)||Date.now(),score:e.score,total:e.total||100}));notice('已导入此网址的旧版本机记录。旧版临时案例编号无法可靠迁移。');}}catch{}await save();}
 render();setupOffline();tick();setInterval(tick,1000);
 if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_local_study_progress',title:'读取本机学习进度',description:'读取当前设备的练习统计，不修改数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');return {practiced:Object.keys(state.done).length,attempts:state.attempts.length,wrong:state.wrong.length,favorites:state.fav.length,exams:state.exams.length,offlineReady:offline};}})).catch(()=>{});}catch{}}
 }catch(e){app.innerHTML=`<section class="panel"><h1>暂时无法打开</h1><p>${esc(e.message)}</p><p>请使用 Safari，保持联网后重新打开。如果之前已有记录，请不要清除网站数据。</p><button class="btn" onclick="location.reload()">重新打开</button></section>`;}}
init();
})();